[package]
name = "emoji-chat-stat"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "emoji2csv"
path = "src/bin/emoji2csv.rs"

[[bin]]
name = "emojicsv2graph"
path = "src/bin/emojicsv2graph.rs"

[dependencies]
chrono = "0.4.38"
csv = "1.3.0"
image = "0.25.2"
plotters = "0.3.6"
regex = "1.10.6"
